# Generated by Django 3.0.7 on 2020-06-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20200627_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('songs', models.ManyToManyField(to='songs.Song')),
            ],
        ),
    ]
