# Generated by Django 3.0.7 on 2020-07-02 09:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0005_auto_20200702_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 11, 55, 15, 4126)),
        ),
        migrations.AddField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 11, 55, 15, 4126)),
        ),
        migrations.AddField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 11, 55, 15, 3126)),
        ),
        migrations.AddField(
            model_name='song',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 11, 55, 15, 3126)),
        ),
    ]
